[package]
name = "prophet-ressa"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
source-code-parser = { git = "https://github.com/cloudhubs/source-code-parser", rev = "b30be50" }
prophet-ressa-minify = { path = "../prophet-ressa-minify" }
tracing = "0.1.26"
actix-web = "3.3.2"
serde = { version = "1.0.118", features = ["derive"] }
serde_json = "1.0.60"
structopt = "0.3.21"
once_cell = "1.7.2"
derive-new = "0.5.8"